package presentacion;

import dto.MedicamentoDTO;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import casoDeUsoAgregar.CasoDeUsoAgregar;
import casoDeUsoAgregar.CasoDeUsoAgregarException;
import casoDeUsoAgregar.ICasoDeUsoAgregar;
import dto.UsuarioDTO;
import java.util.logging.Level;
import java.util.logging.Logger;

public class FormAgregarMedicamento extends javax.swing.JFrame {

    private UsuarioDTO usuarioDTO;
    
    /**
     * Creates new form FormAgregarMedicamento
     */
    public FormAgregarMedicamento(UsuarioDTO usuarioDTO) {
        initComponents();
        this.usuarioDTO = usuarioDTO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFondo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelTitulo1 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelTipoCosumo = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        labelFrecuencia = new javax.swing.JLabel();
        labelPrimeraDosis = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnAgregarMedicamento = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtFrecuencia = new javax.swing.JTextField();
        txtPrimeraDosis = new javax.swing.JTextField();
        cbxTipoConsumo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panFondo.setBackground(new java.awt.Color(204, 255, 255));

        labelTitulo.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelTitulo.setText("Increible Sistema de Toma de Medicamentos");

        labelTitulo1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelTitulo1.setText("Agregar Medicamento");

        labelNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelNombre.setText("Nombre:");

        labelTipoCosumo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelTipoCosumo.setText("Tipo de Consumo:");

        labelCantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelCantidad.setText("Cantidad:");

        labelFrecuencia.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelFrecuencia.setText("Frecuencia:");

        labelPrimeraDosis.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelPrimeraDosis.setText("Hora de Primera Dosis:");

        btnRegresar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnAgregarMedicamento.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnAgregarMedicamento.setText("Agregar Medicamento");
        btnAgregarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMedicamentoActionPerformed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        txtCantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        txtFrecuencia.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtFrecuencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFrecuenciaKeyTyped(evt);
            }
        });

        txtPrimeraDosis.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtPrimeraDosis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrimeraDosisKeyTyped(evt);
            }
        });

        cbxTipoConsumo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cbxTipoConsumo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tableta", "Jarabe" }));

        javax.swing.GroupLayout panFondoLayout = new javax.swing.GroupLayout(panFondo);
        panFondo.setLayout(panFondoLayout);
        panFondoLayout.setHorizontalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panFondoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnRegresar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarMedicamento))
                        .addGroup(panFondoLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelTitulo1)
                                .addComponent(labelTitulo))))
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNombre)
                            .addComponent(labelTipoCosumo)
                            .addComponent(labelCantidad)
                            .addComponent(labelFrecuencia)
                            .addComponent(labelPrimeraDosis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(txtFrecuencia, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(txtPrimeraDosis, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(cbxTipoConsumo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panFondoLayout.setVerticalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitulo1)
                .addGap(29, 29, 29)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoCosumo)
                    .addComponent(cbxTipoConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrimeraDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrimeraDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnAgregarMedicamento))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FormInicio formInicio = new FormInicio(usuarioDTO);
        formInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAgregarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMedicamentoActionPerformed
        if (txtNombre.getText().isEmpty() || txtFrecuencia.getText().isEmpty() || txtPrimeraDosis.getText().isEmpty() || txtCantidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Todos los campos deben estar llenos!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            MedicamentoDTO medicamentoDTO = new MedicamentoDTO(
                    txtNombre.getText(),
                    Double.parseDouble(txtFrecuencia.getText()),
                    Double.parseDouble(txtPrimeraDosis.getText()),
                    cbxTipoConsumo.getSelectedItem().toString(),
                    Integer.parseInt(txtCantidad.getText())
            );

            ICasoDeUsoAgregar casoDeUsoAgregar = new CasoDeUsoAgregar();
            try {
                if (casoDeUsoAgregar.AgregarMedicamento(medicamentoDTO)) {
                    JOptionPane.showMessageDialog(null, "¡Medicamento agregado exitosamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    FormInicio formInicio = new FormInicio(usuarioDTO);
                    formInicio.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo agregar el medicamento. Inténtalo de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (CasoDeUsoAgregarException ex) {
                Logger.getLogger(FormAgregarMedicamento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAgregarMedicamentoActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtFrecuenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFrecuenciaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFrecuenciaKeyTyped

    private void txtPrimeraDosisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimeraDosisKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrimeraDosisKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMedicamento;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxTipoConsumo;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelFrecuencia;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPrimeraDosis;
    private javax.swing.JLabel labelTipoCosumo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JPanel panFondo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFrecuencia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrimeraDosis;
    // End of variables declaration//GEN-END:variables
}
