package presentacion;

import casoDeUsoEditar.CasoDeUsoEditar;
import casoDeUsoEditar.CasoDeUsoEditarException;
import casoDeUsoEditar.ICasoDeUsoEditar;
import dto.MedicamentoDTO;
import dto.UsuarioDTO;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FormEditarMedicamento extends javax.swing.JFrame {

    private String flujo;
    private ICasoDeUsoEditar casoDeUsoEditar;
    private MedicamentoDTO medicamentoDTO;
    private UsuarioDTO usuarioDTO;

    /**
     * Creates new form FormEditarMedicamento
     */
    public FormEditarMedicamento(String flujo, MedicamentoDTO medicamentoDTO, UsuarioDTO usuarioDTO) {
        initComponents();
        this.flujo = flujo;
        this.medicamentoDTO = medicamentoDTO;
        casoDeUsoEditar = new CasoDeUsoEditar();
        this.usuarioDTO = usuarioDTO;

        labelCodigon.setText("" + medicamentoDTO.getCodigo());
        txtNombre.setText(medicamentoDTO.getNombre());
        cbxTipoConsumo.setSelectedItem(medicamentoDTO.getTipoConsumo());
        txtCantidad.setText("" + medicamentoDTO.getCantidad());
        txtFrecuencia.setText("" + medicamentoDTO.getFrecuencia());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFondo4 = new javax.swing.JPanel();
        labelTitulo4 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        labelTitulo5 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        labelTipoCosumo = new javax.swing.JLabel();
        cbxTipoConsumo = new javax.swing.JComboBox<>();
        labelCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        labelFrecuencia = new javax.swing.JLabel();
        txtFrecuencia = new javax.swing.JTextField();
        btnRegresar1 = new javax.swing.JButton();
        labelCodigo = new javax.swing.JLabel();
        labelCodigon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panFondo4.setBackground(new java.awt.Color(204, 255, 255));

        labelTitulo4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelTitulo4.setText("Increible Sistema de Toma de Medicamentos");

        btnRegresar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        labelTitulo5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelTitulo5.setText("Editar Medicamento");

        labelNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelNombre.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        labelTipoCosumo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelTipoCosumo.setText("Tipo de Consumo:");

        cbxTipoConsumo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cbxTipoConsumo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tableta", "mL" }));

        labelCantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelCantidad.setText("Cantidad:");

        txtCantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        labelFrecuencia.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelFrecuencia.setText("Frecuencia:");

        txtFrecuencia.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtFrecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFrecuenciaActionPerformed(evt);
            }
        });
        txtFrecuencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFrecuenciaKeyTyped(evt);
            }
        });

        btnRegresar1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnRegresar1.setText("Editar Medicamento");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        labelCodigo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelCodigo.setText("Codigo:");

        labelCodigon.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelCodigon.setText("xxxx-xxxx-xxxx-xxxx");

        javax.swing.GroupLayout panFondo4Layout = new javax.swing.GroupLayout(panFondo4);
        panFondo4.setLayout(panFondo4Layout);
        panFondo4Layout.setHorizontalGroup(
            panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondo4Layout.createSequentialGroup()
                .addGroup(panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panFondo4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNombre)
                            .addComponent(labelTipoCosumo)
                            .addComponent(labelCantidad)
                            .addComponent(labelFrecuencia)
                            .addComponent(labelCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtFrecuencia)
                            .addComponent(cbxTipoConsumo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCodigon)))
                    .addGroup(panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panFondo4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnRegresar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegresar1))
                        .addGroup(panFondo4Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelTitulo5)
                                .addComponent(labelTitulo4)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panFondo4Layout.setVerticalGroup(
            panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondo4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelTitulo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitulo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigo)
                    .addComponent(labelCodigon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoCosumo)
                    .addComponent(cbxTipoConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnRegresar1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FormObtenerMedicamento formObtenerMedicamento = new FormObtenerMedicamento(flujo, usuarioDTO);
        formObtenerMedicamento.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtFrecuenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFrecuenciaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txtFrecuenciaKeyTyped

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        if (txtNombre.getText().isEmpty() || txtFrecuencia.getText().isEmpty() || txtCantidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Todos los campos deben estar llenos!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            MedicamentoDTO medicamentoNuevoDTO = new MedicamentoDTO(medicamentoDTO.getCodigo(),
                    txtNombre.getText(),
                    Double.parseDouble(txtFrecuencia.getText()),
                    cbxTipoConsumo.getSelectedItem().toString(),
                    Integer.parseInt(txtCantidad.getText())
            );

            try {
                if (casoDeUsoEditar.EditarMedicamento(medicamentoNuevoDTO, usuarioDTO.getCodigo())) {
                    JOptionPane.showMessageDialog(null, "¡Medicamento Editado exitosamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    FormObtenerMedicamento formObtenerMedicamento = new FormObtenerMedicamento(flujo, usuarioDTO);
                    formObtenerMedicamento.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo Editar el medicamento. Inténtalo de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (CasoDeUsoEditarException ex) {
                Logger.getLogger(FormEditarMedicamento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();

        // Si el carácter no es una letra, consumir el evento
        if (!Character.isLetter(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtFrecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFrecuenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFrecuenciaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JComboBox<String> cbxTipoConsumo;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelCodigon;
    private javax.swing.JLabel labelFrecuencia;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTipoCosumo;
    private javax.swing.JLabel labelTitulo4;
    private javax.swing.JLabel labelTitulo5;
    private javax.swing.JPanel panFondo4;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFrecuencia;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
