/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dto.MedicamentoDTO;
import dto.RegistroDTO;
import negocio.RegistroBO;

/**
 *
 * @author ITSON
 */
public class FormProximaDosis extends javax.swing.JFrame {

    private String flujo;
    private MedicamentoDTO medicamentoDTO;
    private RegistroDTO registroDTO;
    private RegistroBO registroBo;
    
    /**
     * Creates new form FormProximaDosis
     */
    public FormProximaDosis(String flujo, MedicamentoDTO medicamentoDTO) {
        initComponents();
        this.flujo = flujo;
        this.medicamentoDTO = medicamentoDTO;
        registroBo = new RegistroBO();
        
        labelNombre.setText("Nombre: "+medicamentoDTO.getNombre());
        labelTipoConsumo.setText("Tipo de Consumo: "+medicamentoDTO.getTipoConsumo());
        labelCantidad.setText("Cantidad: "+medicamentoDTO.getCantidad());
        labelFrecuencia.setText("Frecuencia: "+medicamentoDTO.getFrecuencia());
        labelPrimeraDosis.setText("Hora de Primera Dosis: "+medicamentoDTO.getHoraPrimeraDosis()); 
        //esta madre tampoco se como la quieren hacer, asi que hice que consultara la ultima toma del medicamento
        //y le sumara la frecuencia a la que debe de tomar???? relamente este no va a funcionar XD
        //como dije en el FormTomarMedicamento ahi le buscan q pedo
        labelProximaDosis.setText(""+(registroBo.consultarUltimaToma(medicamentoDTO)+medicamentoDTO.getFrecuencia()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFondo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        labelTitulo1 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelTipoConsumo = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        labelFrecuencia = new javax.swing.JLabel();
        labelPrimeraDosis = new javax.swing.JLabel();
        labelTitulo2 = new javax.swing.JLabel();
        labelProximaDosis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panFondo.setBackground(new java.awt.Color(204, 255, 255));

        labelTitulo.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelTitulo.setText("Increible Sistema de Toma de Medicamentos");

        btnRegresar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        labelTitulo1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelTitulo1.setText("Proxima Dosis");

        labelNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelNombre.setText("Nombre:");

        labelTipoConsumo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelTipoConsumo.setText("Tipo de Consumo:");

        labelCantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelCantidad.setText("Cantidad:");

        labelFrecuencia.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelFrecuencia.setText("Frecuencia:");

        labelPrimeraDosis.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelPrimeraDosis.setText("Hora de Primera Dosis:");

        labelTitulo2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelTitulo2.setText("La proxima Dosis sera en:");

        labelProximaDosis.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelProximaDosis.setText("Error! proxima dosis no encontra D:");

        javax.swing.GroupLayout panFondoLayout = new javax.swing.GroupLayout(panFondo);
        panFondo.setLayout(panFondoLayout);
        panFondoLayout.setHorizontalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar))
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo1)
                            .addComponent(labelTitulo)
                            .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelNombre)
                                .addComponent(labelTipoConsumo)
                                .addComponent(labelCantidad)
                                .addComponent(labelFrecuencia)
                                .addComponent(labelPrimeraDosis))))
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(labelTitulo2))
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(labelProximaDosis)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panFondoLayout.setVerticalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitulo1)
                .addGap(27, 27, 27)
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTipoConsumo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPrimeraDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelProximaDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FormObtenerMedicamento formObtenerMedicamento = new FormObtenerMedicamento(flujo);
        formObtenerMedicamento.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelFrecuencia;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPrimeraDosis;
    private javax.swing.JLabel labelProximaDosis;
    private javax.swing.JLabel labelTipoConsumo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel labelTitulo2;
    private javax.swing.JPanel panFondo;
    // End of variables declaration//GEN-END:variables
}
