/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author ITSON
 */
public class FormEliminarMedicamento extends javax.swing.JFrame {

    /**
     * Creates new form FormEliminarMedicamento
     */
    public FormEliminarMedicamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFondo4 = new javax.swing.JPanel();
        labelTitulo4 = new javax.swing.JLabel();
        btnRegresar4 = new javax.swing.JButton();
        labelTitulo5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panFondo4.setBackground(new java.awt.Color(204, 255, 255));

        labelTitulo4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelTitulo4.setText("Increible Sistema de Toma de Medicamentos");

        btnRegresar4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnRegresar4.setText("Regresar");
        btnRegresar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar4ActionPerformed(evt);
            }
        });

        labelTitulo5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelTitulo5.setText("Eliminar Medicamento");

        javax.swing.GroupLayout panFondo4Layout = new javax.swing.GroupLayout(panFondo4);
        panFondo4.setLayout(panFondo4Layout);
        panFondo4Layout.setHorizontalGroup(
            panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondo4Layout.createSequentialGroup()
                .addGroup(panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondo4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar4))
                    .addGroup(panFondo4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo5)
                            .addComponent(labelTitulo4))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panFondo4Layout.setVerticalGroup(
            panFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondo4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelTitulo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitulo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(btnRegresar4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar4ActionPerformed
        FormInicio formInicio = new FormInicio();
        formInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton btnRegresar2;
    private javax.swing.JButton btnRegresar3;
    private javax.swing.JButton btnRegresar4;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel labelTitulo2;
    private javax.swing.JLabel labelTitulo3;
    private javax.swing.JLabel labelTitulo4;
    private javax.swing.JLabel labelTitulo5;
    private javax.swing.JPanel panFondo;
    private javax.swing.JPanel panFondo1;
    private javax.swing.JPanel panFondo2;
    private javax.swing.JPanel panFondo3;
    private javax.swing.JPanel panFondo4;
    // End of variables declaration//GEN-END:variables
}
